### PR TITLE
fix: Only process owner references for known kinds of owners.

### LINKED ISSUE #244: Unable to get owner of resource object does not deploy sidecar to deployable Kind specified
## Expected Behavior
Operator attaches sidecar to deployable Kind in namespace.

## Actual Behavior
```
2023-03-02T20:14:20Z    INFO    could not get owner     {"owner": "&OwnerReference{Kind:MyCustomResource,Name:custom-resource-thing,UID:66dea891-a7c7-482c-9346-a73822381ede,APIVersion:my.example.com/v1alpha1,Controller:*true,BlockOwnerDeletion:nil,}", "err": "Timeout: failed waiting for *v1.PartialObjectMetadata Informer to sync"}
2023-03-02T20:14:20Z    DEBUG   controller-runtime.webhook.webhooks     wrote response  {"webhook": "/mutate-pods", "code": 500, "reason": "", "UID": "be75e6a4-7d54-4d93-ad3f-6e38a72f807a", "allowed": false}
```

## Steps to Reproduce the Problem

Using this `AuthProxyWorkload` CR, I am using Config Connector but that shouldn't matter here:

```
{{- range $.Values.cloudSQLInstances }}
apiVersion: cloudsql.cloud.google.com/v1alpha1
kind: AuthProxyWorkload
metadata:
  name: {{ template "my-operator.fullname" $ }}
  namespace: mynamespace
  annotations:
    cnrm.cloud.google.com/project-id: {{ $.Values.projectId }}
    cnrm.cloud.google.com/deletion-policy: abandon
  labels:
    {{- include "my-operator.labels" $ | nindent 4 }}
spec:
  workloadSelector:
    kind: "StatefulSet"
    name: "my-deployment"
  instances:
  - connectionString: "{{ $.Values.projectId }}:{{ $.Values.region }}:{{ .instance }}"
    port: 5432
    privateIP: true
{{- end }}
```

## Specifications
```
023-03-02T19:47:57Z    INFO    Starting Cloud SQL Proxy Operator
2023-03-02T19:47:57Z    INFO    Version: 0.3.0 Build: 53b97905ee71b2902fcff985a7a5d414164e7323
2023-03-02T19:47:57Z    INFO    Runtime: go1.20.1 linux/amd64
```

### PR DESCRIPTION
**Pull request by hessjcg**
Pods can be owned by multiple owners. We only want the operator to traverse the owners where it knows
the kind of workload: ReplicaSet, Deployment, etc. We don't want the operator to try to travers other 
kinds of owner resources that it does not understand, because the operator was not granted privileges 
to access those resources. 

Fixes #244

### CODE REVIEW

File: internal/controller/pod_controller.go [hunk 1]
```diff
@@ -49,77 +49,78 @@ func (a *PodAdmissionWebhook) InjectDecoder(d *admission.Decoder) error {
...
-	err := a.decoder.Decode(req, wl.Object())
+	p := corev1.Pod{}
+	err := a.decoder.Decode(req, &p)
 	if err != nil {
 		l.Info("/mutate-pod request can't be processed",
 			"kind", req.Kind.Kind, "ns", req.Namespace, "name", req.Name)
 		return admission.Errored(http.StatusInternalServerError, err)
 	}
 
+	updatedPod, err := a.handleCreatePodRequest(ctx, p)
```
Comment (hessjcg) [inline internal/controller/pod_controller.go:60]: I split the Handle function into 2 separate responsibilities:
- `func Handle(ctx, req)` does all the transformation between `admission.Request` and `admission.Response` into useful domain objects. 
- `func handleCreatePodRequest(ctx, pod)` has the business logic to decide when and how to add Proxy containers to a pod as it is being created.

This made it a lot easier to write unit tests for the business logic without having to implement a lot of extraneous json handling code.

File: internal/controller/pod_controller_test.go [hunk 2]
```diff
@@ -0,0 +1,153 @@
...
+	appsv1 "k8s.io/api/apps/v1"
+	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/types"
+	"sigs.k8s.io/controller-runtime/pkg/client"
+	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
+	"sigs.k8s.io/controller-runtime/pkg/log"
+	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
+)
+
+func TestPodWebhookWithDeploymentOwners(t *testing.T) {
```
Comment (hessjcg) [inline internal/controller/pod_controller_test.go:33]: This is the new unit test for the pod create webhook business logic.

File: internal/controller/pod_controller_test.go [hunk 3]
```diff
@@ -0,0 +1,153 @@
...
+			wantUpdate: true,
+		},
+		{
+			name:       "Deployment Pod with no match",
+			p:          p,
+			d:          dNoMatch,
+			wantUpdate: false,
+		},
+		{
+			name:       "Deployment Pod with unknown owner",
```
Comment (hessjcg) [inline internal/controller/pod_controller_test.go:95]: This is the test case for the bug fix.

File: internal/controller/pod_controller_test.go [hunk 4]
```diff
@@ -0,0 +1,153 @@
...
+	dNoMatch.ObjectMeta.Labels = map[string]string{"app": "other"}
+
+	// Deployment that matches the proxy with an owner of an unknown kind
+	dWithOwner := testhelpers.BuildDeployment(types.NamespacedName{
+		Namespace: "default",
+		Name:      "test",
+	}, "webapp")
+	dWithOwner.ObjectMeta.Labels = map[string]string{"app": "webapp"}
+	deploymentOwner := &v1.PartialObjectMetadata{
+		TypeMeta:   v1.TypeMeta{Kind: "BuildToolOperatror", APIVersion: "v1"},
```
Comment (enocom) [inline internal/controller/pod_controller_test.go:68]: sp: BuildToolOperatror

nit: Maybe just "DontTouchThisThing" or something obviously not of a known kind. BuildToolOperator looks legit.

File: internal/controller/pod_controller_test.go [hunk 5]
```diff
@@ -0,0 +1,153 @@
...
+			name:       "Deployment Pod with no match",
+			p:          p,
+			d:          dNoMatch,
+			wantUpdate: false,
+		},
+		{
+			name:       "Deployment Pod with unknown owner",
+			p:          p,
+			d:          dWithOwner,
+			wantUpdate: true,
```
Comment (enocom) [inline internal/controller/pod_controller_test.go:98]: Should this be false?

Comment (hessjcg) [reply internal/controller/pod_controller_test.go:98]: No, this should be true. The AuthProxyWorkload should act on the Deployment's pods, even if the deployment is owned by a different operator. We have a user who wants the Cloud SQL Proxy Operator to add proxy containers to pods that are related to a deployment managed by another operator.

Comment (enocom) [reply internal/controller/pod_controller_test.go:98]: Is there a test covering the change you made to ignoring owners of an unknown kind in that case?

File: internal/controller/pod_controller_test.go (hunk 4 above)
Comment (hessjcg) [reply internal/controller/pod_controller_test.go]: Fixed. I added more comments to make this easier to understand.

File: internal/controller/pod_controller_test.go (hunk 5 above)
Comment (hessjcg) [reply internal/controller/pod_controller_test.go:99]: Yes, this is that test.

**Review by enocom — APPROVED** [review]
