### PR TITLE
fix: delete misconfigured pods in error state.

### LINKED ISSUE #337: Delete workloads pods that are missing an proxy container when they are in an error state
The operator uses a webhook to add the proxy container to pods. The webhook is setup with `failurePolicy: Ignore`. This was an intentional design choice. It allows pods to be created when the operator is not receiving webhook requests.  (If you create a webhook for all pods with `failurePolicy: Fail`, then when the pods serving that webhook are terminated, the cluster will be unable to start new pods, including the replacement pods for that webhook.)

Unfortunately this means that occasionally a pod related to a workload will be created without the operator adding the proxy sidecar container. This could happen if there is a bug in the webhook causing it to return an error response. This could also happen when all the operator pods are offline, for example when the cluster replaces a node which happens to be running all the operator pods. 

The best solution for now is to program the operator to delete improperly configured pods. The operator will listen for events on all pods related to known AuthProxyWorkloads. If such a pod exits in error, the operator will check the pod resource for the proxy sidecar container. If the proxy sidecar container is missing, the operator will delete the pod. 

In the future, we can use the webhook [matchConditions](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-matchconditions) with `failurePolicy: Fail` to ensure that the webhook only filters pods related to AuthProxyWorklod, not all pods in the cluster. This k8s feature is alpha in v1.27, so we can't use it yet.

### PR DESCRIPTION
**Pull request by hessjcg**
The pod cannot be configured to reliably instrument every single pod creation event due to limitations in the K8s API. 
Thus, the operator needs to listen for pod create and update events, to check if the pod is configured correctly. If the
pod is not configured correctly, and the pod is in an error or waiting state, the operator will delete the pod so that it can
be replaced. The replacement pod will be correctly configured by the webhook as it is created. 

Fixes #337

### CODE REVIEW

File: internal/controller/pod_controller.go [hunk 1]
```diff
@@ -81,51 +84,68 @@ func (a *PodAdmissionWebhook) Handle(ctx context.Context, req admission.Request)
 // handleCreatePodRequest Finds relevant AuthProxyWorkload resources and updates the pod
 // with matching resources, returning a non-nil pod when the pod was updated.
 func (a *PodAdmissionWebhook) handleCreatePodRequest(ctx context.Context, p corev1.Pod) (*corev1.Pod, error) {
+	l := logf.FromContext(ctx)
```
Comment (hessjcg) [inline internal/controller/pod_controller.go:87]: This change moves code from the `handleCreatePodRequest()` function into a new function called `findMatchingProxies()` so that it can be reused between the webhook and the new Pod event listener.

File: internal/controller/pod_controller.go [hunk 2]
```diff
@@ -81,51 +84,68 @@ func (a *PodAdmissionWebhook) Handle(ctx context.Context, req admission.Request)
...
-	}
+	return proxies, nil
 
-	return wl.Pod, nil // updated
 }
 
 // listOwners returns the list of this object's owners and its extended owners.
 // Warning: this is a recursive function
-func (a *PodAdmissionWebhook) listOwners(ctx context.Context, object client.Object) ([]workload.Workload, error) {
+func listOwners(ctx context.Context, c client.Client, object client.Object) ([]workload.Workload, error) {
```
Comment (hessjcg) [inline internal/controller/pod_controller.go:148]: This refactors `listOwners()` from a member of `PodAdmissionWebhook` to a plain function so that it can be used both in the webhook and the pod event listener.

File: internal/controller/pod_controller.go [hunk 3]
```diff
@@ -168,3 +188,104 @@ func (a *PodAdmissionWebhook) listOwners(ctx context.Context, object client.Obje
 	}
 	return owners, nil
 }
+
```
Comment (hessjcg) [inline internal/controller/pod_controller.go:191]: This is the new pod event listener implementation.

File: internal/controller/setup.go [hunk 4]
```diff
@@ -71,6 +71,11 @@ func SetupManagers(mgr manager.Manager, userAgent, defaultProxyImage string) err
 		setupLog.Error(err, "unable to create workload admission webhook controller")
 		return err
 	}
+	err = registerPodInformer(mgr, u)
```
Comment (hessjcg) [inline internal/controller/setup.go:74]: Register the PodEventHandler when the operator starts up.

**Comment by jackwotherspoon** [comment]
@hessjcg Is it possible to add tests for this to make sure `PodEventHandler` is WAI?

**Comment by enocom** [comment]
Does this fix https://github.com/GoogleCloudPlatform/cloud-sql-proxy-operator/issues/337?

**Comment by hessjcg** [comment]
@enocom, Yes this fixes #337.
@jackwotherspoon, I added some unit tests in `pod_controller_test.go`

**Comment by enocom** [comment]
Updated the title to reflect what we're doing here.

File: internal/controller/pod_controller.go [hunk 5]
```diff
@@ -168,3 +189,116 @@ func (a *PodAdmissionWebhook) listOwners(ctx context.Context, object client.Obje
...
+// PodEventHandlerRunner starts a PodEventHandler when the manager
+// begins, ensuring that it only runs on the leader operator pod.
+type PodEventHandlerRunner struct {
```
Comment (enocom) [inline internal/controller/pod_controller.go:195]: Does this need to be exported?

File: internal/controller/pod_controller.go [hunk 6]
```diff
@@ -168,3 +189,116 @@ func (a *PodAdmissionWebhook) listOwners(ctx context.Context, object client.Obje
...
+	}
+	return nil
+
+}
+
+// PodEventHandler receives pod changed events for all pods in the K8s cluster
+// to ensure that any pods that should have proxy sidecars are configured
+// correctly. If a pod is not configured correctly, and is not running, then
+// the operator will delete the pod.
+type PodEventHandler struct {
```
Comment (enocom) [inline internal/controller/pod_controller.go:239]: Same here. Does this need to be exported?

File: internal/controller/pod_controller.go [hunk 7]
```diff
@@ -168,3 +189,116 @@ func (a *PodAdmissionWebhook) listOwners(ctx context.Context, object client.Obje
...
+	ctx context.Context
+	c   client.Client
+	u   *workload.Updater
+	l   logr.Logger
+}
+
+// OnAdd is called by the informer when a Pod is added.
+func (h *PodEventHandler) OnAdd(obj interface{}) {
```
Comment (enocom) [inline internal/controller/pod_controller.go:247]: Is this and the following methods part of an interface that Kubernetes uses?

File: internal/controller/setup.go [hunk 8]
```diff
@@ -94,3 +99,15 @@ func RegisterPodWebhook(mgr ctrl.Manager, u *workload.Updater) error {
 
 	return nil
 }
+
+// registerPodInformer sets up the informer so that the operator is
+// notified on all changes to all pod resources.
+func registerPodInformer(mgr ctrl.Manager, u *workload.Updater) error {
+	h := &PodEventHandlerRunner{
```
Comment (enocom) [inline internal/controller/setup.go:106]: nit: an initializer would be nice here since the zero value isn't usable.

**Review by hessjcg — COMMENTED** [review]
Updated in response to @enocom

**Review by enocom — COMMENTED** [review]
LGTM. I'd like @pwschuurman to approve this one just to make sure we have the logic and nuances right here.

**Review by enocom — COMMENTED** [review]
LGTM. I'd like @pwschuurman to approve this one just to make sure we have the logic and nuances right here.

File: internal/controller/pod_controller.go [hunk 9]
```diff
@@ -168,3 +189,136 @@ func (a *PodAdmissionWebhook) listOwners(ctx context.Context, object client.Obje
...
+type podEventHandler struct {
+	ctx context.Context
+	c   client.Client
+	u   *workload.Updater
+	l   logr.Logger
+}
+
+// OnAdd implements cache.ResourceEventHandler, gets called by the cache
+// informer when a Pod is added to the k8s cluster.
+func (h *podEventHandler) OnAdd(obj interface{}) {
```
Comment (pwschuurman) [inline internal/controller/pod_controller.go:263]: Does OnAdd() events also trigger when the mutating webhook triggers? I'm wondering if pod objects might be processed twice.

File: internal/controller/pod_controller.go [hunk 10]
```diff
@@ -168,3 +189,136 @@ func (a *PodAdmissionWebhook) listOwners(ctx context.Context, object client.Obje
...
+	}
+	return nil
+
+}
+
+// podEventHandler receives pod changed events for all pods in the K8s cluster
+// to ensure that any pods that should have proxy sidecars are configured
+// correctly. If a pod is not configured correctly, and is not running, then
+// the operator will delete the pod.
+type podEventHandler struct {
```
Comment (pwschuurman) [inline internal/controller/pod_controller.go:254]: The other possible architecture here is to have a controller for your different resources (AuthProxyWorkload, Pod). And then when you get events for pods, you can filter these back to the main workload. You can use event handlers to process events, and perform the actual CRUD work in a controller Reconcile() function. The benefit of this pattern is that Reconcile() functions return an error, which can be retried, while handler functions do not return an error.

File: internal/controller/pod_controller.go (hunk 9 above)
Comment (pwschuurman) [reply internal/controller/pod_controller.go:263]: Discussed offline. OnAdd will preform a no-op reprocessing after the mutating webhook modifies a pod.

File: internal/controller/pod_controller.go [hunk 11]
```diff
@@ -168,3 +189,136 @@ func (a *PodAdmissionWebhook) listOwners(ctx context.Context, object client.Obje
...
+func (r *podEventHandlerRunner) NeedLeaderElection() bool {
+	return true
+}
+
+// Start implements manager.Runnable which will start the informer receiving
+// pod change events on the operator's leader instance.
+func (r *podEventHandlerRunner) Start(ctx context.Context) error {
+	h := newPodEventHandler(ctx, r.mgr.GetClient(), r.u, r.l)
+
+	i, err := r.mgr.GetCache().GetInformerForKind(ctx, schema.GroupVersionKind{
```
[the remark this answers is not in the document]
Comment (pwschuurman) [reply internal/controller/pod_controller.go:233]: Discussed Offline:
1. Filtering: This gets tricky, as filtering predicates would need to be added per AuthProxyWorkload. The workload resources (Deployment, StatefulSet) would need to be traversed to determine their pod selector, which could be used as a predicate. This could be done using a controler Watch() function, but it isn't clear if controller-runtime is architected to scale the number of watch events per pod selector. This also increases the complexity of the operator logic, and without a clear customer impacting issue, it isn't worth optimizing yet.
2. Cache Initialization: From empirical testing, the handler re-processes events of existing resources when the controller starts up.

File: internal/controller/pod_controller.go (hunk 10 above)
Comment (pwschuurman) [reply internal/controller/pod_controller.go:254]: Discussed Offline: Moving the processing to a Reconcile() function is a potential benefit, that will be investigated in a future PR.

**Review by pwschuurman — APPROVED** [review]

**Comment by hessjcg** [comment]
@enocom This needs an "Approve" review from you before I can merge it, since @pwschuurman is not a code owner.

File: internal/controller/pod_controller.go [hunk 12]
```diff
@@ -168,3 +189,84 @@ func (a *PodAdmissionWebhook) listOwners(ctx context.Context, object client.Obje
...
+	if err != nil {
+		return fmt.Errorf("unable to find proxies when pod changed, %v", err)
+	}
+
+	// There are no proxies, ignore this event.
+	if len(proxies) == 0 {
+		return nil
+	}
+
+	// Check if this pod is in error and missing proxy containers
```
Comment (jackwotherspoon) [inline internal/controller/pod_controller.go:257]: add detail here? is `in error` the proper wording? `in error state` perhaps? 
```suggestion
	// Check if this pod is in error state and missing proxy containers
```

File: internal/controller/pod_controller.go [hunk 13]
```diff
@@ -168,3 +189,84 @@ func (a *PodAdmissionWebhook) listOwners(ctx context.Context, object client.Obje
...
+	wlConfigErr := r.updater.CheckWorkloadContainers(wl, proxies)
+
+	// If this pod is in error, delete it. Simply logging an error is sufficient.
```
Comment (jackwotherspoon) [inline internal/controller/pod_controller.go:260]: same here should we be saying `in error`?

File: internal/controller/pod_controller.go [hunk 14]
```diff
@@ -168,3 +189,84 @@ func (a *PodAdmissionWebhook) listOwners(ctx context.Context, object client.Obje
...
 	return owners, nil
 }
+
+type podDeleteController struct {
+	client.Client
+	Scheme  *runtime.Scheme
+	updater *workload.Updater
+}
+
+// newDeletePodController constructs an podDeleteController
```
[the remark this answers is not in the document]
Comment (hessjcg) [reply internal/controller/pod_controller.go]: fixed.

File: internal/controller/pod_controller.go (hunk 12 above)
Comment (hessjcg) [reply internal/controller/pod_controller.go]: fixed.

File: internal/controller/pod_controller.go (hunk 13 above)
Comment (hessjcg) [reply internal/controller/pod_controller.go]: fixed.

**Review by jackwotherspoon — APPROVED** [review]
